ShoppingService/Controllers/ChatsController.cs
using System.Security.Claims;
using ChatService;
using Grpc.Core;
using Grpc.Net.Client;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ShoppingService.Data;
using ShoppingService.Models;
using ShoppingService.Models.Dto;
using ShoppingService.Models.Enum;

namespace ShoppingService.Controllers
{
    [Authorize]
    [Route("chat")]
    public class ChatsController : Controller
    {
        private readonly ShoppingDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly GrpcChannel _grpcChannel;

        public ChatsController(ShoppingDbContext context, 
            UserManager<User> userManager,
            GrpcChannel grpcChannel)
        {
            _context = context;
            _userManager = userManager;
            _grpcChannel = grpcChannel ?? throw new ArgumentNullException(nameof(grpcChannel));
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> ChatInit()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            if (userEmail == null)
                return View("Error", new ErrorViewModel { ErrorMessage = "Unauthorized access." });

            var user = await _userManager.FindByEmailAsync(userEmail);
            if (user == null)
                return View("Error", new ErrorViewModel { ErrorMessage = "User not found." });
            
            ViewBag.Sender = user;
            ViewBag.Receiver = null;

            var filteredUsers = await GetFilteredUsersByRole();
            ViewBag.isAdmin = User.IsInRole(Roles.Admin.ToString());
            
            return View(filteredUsers);
        }

        [HttpGet]
        [Route("{receiverId}")]
        public async Task<IActionResult> ChatOneUser(string receiverId)
        {
            if (string.IsNullOrEmpty(receiverId)) 
                return View("Error", new ErrorViewModel { ErrorMessage = "User ID is required." });

            var senderEmail = User.FindFirstValue(ClaimTypes.Email);
            if (senderEmail == null)
                return View("Error", new ErrorViewModel { ErrorMessage = "Unauthorized access." });

            var sender = await _userManager.FindByEmailAsync(senderEmail);
            if (sender == null)
                return View("Error", new ErrorViewModel { ErrorMessage = "User not found." });

            if (sender.Id == receiverId)
                return View("Error", new ErrorViewModel { ErrorMessage = "You cannot chat with yourself." });

            var receiver = await _userManager.FindByIdAsync(receiverId);
            if (receiver == null)
                return View("Error", new ErrorViewModel { ErrorMessage = "User not found." });

            if (await HaveSameRoleAsync(sender, receiver))
                return View("Error", new ErrorViewModel { ErrorMessage = "You cannot chat with a user that has the same role as you." });
            
            ViewBag.Receiver = receiver;
            ViewBag.Sender = sender;
            
            var request = new ChatRequest() { SenderId = sender.Id, ReceiverId = receiver.Id };
            var client = new Greeter.GreeterClient(_grpcChannel);
            using var call = client.GetChatMessages(request);
            List<ChatResponse> messages = new List<ChatResponse>();

            await foreach (var message in call.ResponseStream.ReadAllAsync())
            {
                messages.Add(message);
            }
            ViewBag.Messages = messages;
            ViewBag.isAdmin = User.IsInRole(Roles.Admin.ToString());

            var filteredUsers = await GetFilteredUsersByRole();
            return View(filteredUsers);
        }

        private async Task<List<User>> GetFilteredUsersByRole()
        {
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            if (userEmail == null) return new List<User>();

            var user = await _userManager.FindByEmailAsync(userEmail);
            if (user == null) return new List<User>();

            var isAdmin = await _userManager.IsInRoleAsync(user, Roles.Admin.ToString());
            var targetRole = isAdmin ? Roles.Client.ToString() : Roles.Admin.ToString();

            return (await _userManager.GetUsersInRoleAsync(targetRole)).ToList();
        }

        private async Task<bool> HaveSameRoleAsync(User user1, User user2)
        {
            var rolesUser1 = await _userManager.GetRolesAsync(user1);
            var rolesUser2 = await _userManager.GetRolesAsync(user2);

            return rolesUser1.Intersect(rolesUser2).Any(); 
        }

        
        private List<object> GetDemoMessages()
        {
            return new List<object>
            {
                new { Text = "Hello!", Time = "10:00 AM", Sender = "other" },
                new { Text = "Hi there!", Time = "10:05 AM", Sender = "self" }
            };
        }
    }
}

ShoppingService/Views/Chats/ChatInit.cshtml
@model IEnumerable<ShoppingService.Models.User>

@{
    ViewBag.Title = "Chat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="Chat">
    <div class="chat-app">
        <div id="chat-sidebar" class="chat-sidebar">
            <div class="sidebar-header">
                <h2>@ViewBag.Sender.FirstName</h2>
            </div>
            <ul id="userList" class="user-list">
                @foreach (var user in Model)
                {
                    <li class="user">
                        <a asp-controller="Chats" asp-action="ChatOneUser" asp-route-receiverId="@user.Id">
                            <span class="user-name">@user.FirstName @user.LastName</span>
                            <span class="last-message">Last message here //TO do</span>
                        </a>
                    </li>
                }
            </ul>
        </div>
        <div id="chat-main" class="chat-main">
            <div class="chat-header">
                <h2>
                    <span>Select a user</span>
                </h2>
            </div>
            <div class="chat-messages">
            </div>
        </div>
    </div>
</section>

<link rel="stylesheet" href="~/css/Chats/Chat.css" asp-append-version="true"/>

ShoppingService/Views/Chats/ChatOneUser.cshtml
@model IEnumerable<ShoppingService.Models.User>

@{
    ViewBag.Title = "Chat";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var sender = ViewBag.Sender;
    var receiver = ViewBag.Receiver;
}

<section id="Chat">
    <div class="chat-app">
        <div id="chat-sidebar" class="chat-sidebar">
            <div class="sidebar-header">
                <h2>@sender.FirstName</h2>
            </div>
            <ul id="userList" class="user-list">
                @foreach (var user in Model)
                {
                    <a asp-controller="Chats" asp-action="ChatOneUser" asp-route-receiverId="@user.Id">
                        <li class="user @(user.Id == receiver.Id ? "active" : "")">
                            <span class="user-name">@user.FirstName @user.LastName</span>
                            <span class="last-message">Last message here //TO do</span>
                        </li>
                    </a>
                }
            </ul>
        </div>
        <div id="chat-main" class="chat-main">
            <div class="chat-header">
                <h2>
                    <span>@receiver.Email</span>
                    <input id="senderId" type="hidden" value="@sender.Id" />
                    <input id="receiverId" type="hidden" value="@receiver.Id" />
                </h2>
            </div>
            <div id="messagesList" class="chat-messages">
                @foreach(var item in ViewBag.Messages)
                {
                    <div class="message @(sender.Id == item.UserId ? "message-sent" : "message-received")">
                        <p class="message-text">@item.Content</p>
                        <span class="message-time">@item.SentAt.Hour:@item.SentAt.Minute</span>
                    </div>
                }
            </div>

            <div class="chat-input">
                <input id="messageToSend" type="text" placeholder="Type a message..."/>
                <button id="sendButton" type="button">Send</button>
            </div>
        </div>
    </div>
</section>

<link rel="stylesheet" href="~/css/Chats/Chat.css" asp-append-version="true"/>
<script src="~/lib/signalr/signalr.js"></script>
<script src="~/lib/signalr/signalr.min.js"></script>
<script src="~/js/Chat.js"></script>